{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rustik.fullname" . }}-metrics-fetcher
  labels:
    {{- include "rustik.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "rustik.fullname" . }}-metrics-fetcher
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress: []
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "rustik.fullname" . }}-metrics-cache
      ports:
        - protocol: TCP
          port: {{ .Values.metricsCache.intraClusterPort }}
    {{- with (concat .Values.networkPolicy.egress.commonRules .Values.networkPolicy.egress.metricsFetcherRules) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
