apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "checkmk-agent.labels" . | nindent 4 }}
  name: {{ include "checkmk-agent.fullname" . }}-cluster-aggregator-pull
  {{- with .Values.clusterAggregator.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.clusterAggregator.service.type }}
  {{- if or (eq .Values.clusterAggregator.service.type "NodePort") (eq .Values.clusterAggregator.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.clusterAggregator.service.externalTrafficPolicy }}
  {{- end }}
  {{- if eq .Values.clusterAggregator.service.type "LoadBalancer" }}
  {{- with .Values.clusterAggregator.service.loadBalancerClass }}
  loadBalancerClass: {{ . | quote }}
  {{- end }}
  {{- with .Values.clusterAggregator.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ include "checkmk-agent.fullname" . }}-cluster-aggregator
  ports:
    - name: pull
      port: {{ .Values.clusterAggregator.service.pullPort }}
      targetPort: pull
      {{- if and .Values.clusterAggregator.service.nodePort (or (eq .Values.clusterAggregator.service.type "NodePort") (eq .Values.clusterAggregator.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.clusterAggregator.service.nodePort }}
      {{- end }}
      protocol: TCP
