apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "checkmk-agent.labels" . | nindent 4 }}
  name: {{ include "checkmk-agent.fullname" . }}-cluster-aggregator-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "checkmk-agent.fullname" . }}-cluster-aggregator-secret
subjects:
  - kind: ServiceAccount
    name: {{ include "checkmk-agent.serviceAccountName" (dict "root" . "component" "cluster-aggregator" "serviceAccount" .Values.clusterAggregator.serviceAccount) }}
    namespace: {{ .Release.Namespace }}
