{{- if .Values.clusterAggregator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.clusterAggregator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "checkmk-agent.labels" . | nindent 4 }}
  name: {{ include "checkmk-agent.serviceAccountName" (dict "root" . "component" "cluster-aggregator" "serviceAccount" .Values.clusterAggregator.serviceAccount) }}
{{- end }}
