{{- if .Values.metricsCache.ingress.enabled }}
{{- if not .Values.pull.enabled }}
{{- fail "metricsCache.ingress.enabled requires pull.enabled" }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rustik.fullname" . }}-metrics-cache
  labels:
    {{- include "rustik.labels" . | nindent 4 }}
  {{- with .Values.metricsCache.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.metricsCache.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.metricsCache.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.metricsCache.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "rustik.fullname" $ }}-metrics-cache-pull
                port:
                  number: {{ $.Values.metricsCache.service.pullPort }}
          {{- end }}
    {{- end }}
{{- end }}
