{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rustik.fullname" . }}-metrics-cache
  labels:
    {{- include "rustik.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "rustik.fullname" . }}-metrics-cache
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "rustik.fullname" . }}-metrics-fetcher
      ports:
        - protocol: TCP
          port: {{ .Values.metricsCache.intraClusterPort }}
    {{- if and .Values.pull.enabled .Values.networkPolicy.pullFrom }}
    - from:
        {{- toYaml .Values.networkPolicy.pullFrom | nindent 8 }}
      ports:
        - protocol: TCP
          port: {{ .Values.metricsCache.pullPort }}
    {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- toYaml (concat .Values.networkPolicy.egress.commonRules .Values.networkPolicy.egress.metricsCacheRules) | nindent 4 }}
  {{- end }}
{{- end }}
