{{- if .Values.metricsCache.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.metricsCache.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "rustik.labels" . | nindent 4 }}
  name: {{ include "rustik.serviceAccountName" (dict "root" . "component" "metrics-cache" "serviceAccount" .Values.metricsCache.serviceAccount) }}
{{- end }}
